### ISSUE TITLE
Removing last site in category breaks the category

### ISSUE THREAD

**Issue by dbwiddis** [SwiddisZwei/strt#16]
Steps to reproduce:
1. Add a new site/category: `+a i inside <url>`
2. Remove the site: `-ai`
3. Attempt to add the site again: `+a i inside <url>`

Expected action:
 - The site returns to its condition after step 1

Observed action:
 - Nothing happens: the category menu remains with nothing under it

Alternate steps to reproduce:
 - Remove the w3schools link from the default config (`-ew`) and then try to add it back.

Workaround:
 - Use `-a` to remove the whole category (undocumented)

OS/Browser:
 - Windows 10 64-bit, Firefox 64.0

**Comment by Swiddis** [comment]
Fixed in #18
