### ISSUE TITLE
Allow for alt+enter to open in new tab

### ISSUE THREAD

**Issue by 7UR7L3** [SwiddisZwei/strt#5]
Similar to Chrome's omnibar, let you keep this start page open always so you don't have to open a new tab to return to the start page every time. I might be the only one who does this but I keep my new tab page always open as the first tab in my browsing windows.

**Comment by Swiddis** [comment]
Implemented in #9 with shift+enter as it's more comfortable and alt+enter conflicts with existing shortcuts on firefox.
